/**
 * Interface for the Natural Language (LLM) service.
 * Follows the Dependency Inversion Principle (DIP).
 */
public interface LLMService {
    /**
     * Generates a response based on a context and a question.
     * 
     * @param context  List of relevant text chunks.
     * @param question The user's query.
     * @return Response generated by the model.
     */
    String generateResponse(java.util.List<String> context, String question);
}
